import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Date from '../components/date'
import { getSortedPostsData } from '../lib/posts'
import Layout, {siteTitle} from '../components/layout'
import utilStyles from '../styles/utils.module.css'
import BlogpostInfo from '../components/blogpost'

export async function getStaticProps() {
  const allPostsData = getSortedPostsData()
  return {
    props: {
      allPostsData
    }
  }
}

export default function Home({ allPostsData }) {
  return (
    <Layout home>
      <Head>
        <title>{siteTitle}</title>
      </Head>
      <p>
        Literally only writing about things I find interesting. Atleast 25% of this text was generated by an AI.
        So if you're reading this, you're probably <i>not</i> interested in the rest of the text.
      </p>
      <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
        <h2 className={utilStyles.headingLg}>Posts</h2>
        <ul className={utilStyles.list}>
          {allPostsData.map((post) => (
            <BlogpostInfo post={post}/>
          ))}
        </ul>
      </section>
    </Layout>
  )
}
